export const TEMPLE_STATE_LIST = [
  {id: 1, state: 'Andhra Pradesh', image: ''},
  {id: 2, state: 'Assam', image: ''},
  {id: 3, state: 'Delhi', image: ''},
  {id: 4, state: 'Bihar', image: ''},
  {id: 5, state: 'Goa', image: ''},
  {id: 6, state: 'Gujarat', image: ''},
  {id: 7, state: 'Haryana', image: ''},
  {id: 8, state: 'Karnataka', image: ''},
  {id: 9, state: 'Madhya Pradesh', image: ''},
  {id: 10, state: 'Maharashtra', image: ''},
  {id: 11, state: 'Punjab', image: ''},
  {id: 12, state: 'Rajasthan', image: ''},
  {id: 13, state: 'Uttarakhand', image: ''},
  {id: 14, state: 'Uttar Pradesh', image: ''},
  {id: 15, state: 'West Bengal', image: ''},
];

export const TEMPLE_DESCRIPTION = [
  {
    id: 1,
    name: 'Venkateswara Temple, Tirumala',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Tirumala_090615.jpg/800px-Tirumala_090615.jpg',
    Affiliation: 'Hinduism',
    District: 'Chittoor',
    Deity: 'Venkateswara (Vishnu)',
    Festivals: 'Brahmotsavam, Vaikunta Ekadasi, Ratha Saptami',
    Governing_body: 'Tirumala Tirupati',
    Location: 'Tirupati',
    State: 'Andhra Pradesh',
    Country: 'India',
  },
  {
    id: 1,
    name: 'Padmavathi Temple',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Padmavathi_Ammavari_Temple.JPG/450px-Padmavathi_Ammavari_Temple.JPG',
    Affiliation: 'Hinduism',
    District: 'Chittoor',
    Deity: 'Padmavathi',
    Festivals: 'Brahmotsavam, Panchami Teertham, Varalakshmi Vratam',
    Governing_body: 'Tirumala Tirupati Devasthanams',
    Location: 'Tiruchanur, Tirupati',
    State: 'Andhra Pradesh',
    Country: 'India',
  },
  {
    id: 1,
    name: 'Mallikarjuna Temple, Srisailam',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Srisailam.jpg/450px-Srisailam.jpg',
    affiliation: 'Hinduism',
    District: 'Srisailam',
    Deity: 'Mallikarjuna (Shiva) Bhramari/Bhrambaramba (Parvati)',
    Festivals: 'Maha Shivaratri, Navratri',
    Governing_body: '',
    Location: 'Srisailam',
    State: 'Andhra Pradesh',
    Country: 'India',
  },
  {
    id: 1,
    name: 'Govindaraja Temple, Tirupati',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
  {
    id: 1,
    name: '',
    image: '',
    affiliation: '',
    District: '',
    Deity: '',
    Festivals: '',
    Governing_body: '',
    Location: '',
    State: '',
    Country: '',
  },
];
